// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plms-backend/ent/lab"
	"plms-backend/ent/lab_problem"
	"plms-backend/ent/predicate"
	"plms-backend/ent/testcase"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LabProblemQuery is the builder for querying Lab_Problem entities.
type LabProblemQuery struct {
	config
	ctx           *QueryContext
	order         []lab_problem.OrderOption
	inters        []Interceptor
	predicates    []predicate.Lab_Problem
	withLab       *LabQuery
	withTestcases *TestcaseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LabProblemQuery builder.
func (lpq *LabProblemQuery) Where(ps ...predicate.Lab_Problem) *LabProblemQuery {
	lpq.predicates = append(lpq.predicates, ps...)
	return lpq
}

// Limit the number of records to be returned by this query.
func (lpq *LabProblemQuery) Limit(limit int) *LabProblemQuery {
	lpq.ctx.Limit = &limit
	return lpq
}

// Offset to start from.
func (lpq *LabProblemQuery) Offset(offset int) *LabProblemQuery {
	lpq.ctx.Offset = &offset
	return lpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lpq *LabProblemQuery) Unique(unique bool) *LabProblemQuery {
	lpq.ctx.Unique = &unique
	return lpq
}

// Order specifies how the records should be ordered.
func (lpq *LabProblemQuery) Order(o ...lab_problem.OrderOption) *LabProblemQuery {
	lpq.order = append(lpq.order, o...)
	return lpq
}

// QueryLab chains the current query on the "lab" edge.
func (lpq *LabProblemQuery) QueryLab() *LabQuery {
	query := (&LabClient{config: lpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lab_problem.Table, lab_problem.FieldID, selector),
			sqlgraph.To(lab.Table, lab.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, lab_problem.LabTable, lab_problem.LabColumn),
		)
		fromU = sqlgraph.SetNeighbors(lpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTestcases chains the current query on the "testcases" edge.
func (lpq *LabProblemQuery) QueryTestcases() *TestcaseQuery {
	query := (&TestcaseClient{config: lpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lab_problem.Table, lab_problem.FieldID, selector),
			sqlgraph.To(testcase.Table, testcase.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lab_problem.TestcasesTable, lab_problem.TestcasesColumn),
		)
		fromU = sqlgraph.SetNeighbors(lpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lab_Problem entity from the query.
// Returns a *NotFoundError when no Lab_Problem was found.
func (lpq *LabProblemQuery) First(ctx context.Context) (*Lab_Problem, error) {
	nodes, err := lpq.Limit(1).All(setContextOp(ctx, lpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lab_problem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lpq *LabProblemQuery) FirstX(ctx context.Context) *Lab_Problem {
	node, err := lpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Lab_Problem ID from the query.
// Returns a *NotFoundError when no Lab_Problem ID was found.
func (lpq *LabProblemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lpq.Limit(1).IDs(setContextOp(ctx, lpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lab_problem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lpq *LabProblemQuery) FirstIDX(ctx context.Context) int {
	id, err := lpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lab_Problem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lab_Problem entity is found.
// Returns a *NotFoundError when no Lab_Problem entities are found.
func (lpq *LabProblemQuery) Only(ctx context.Context) (*Lab_Problem, error) {
	nodes, err := lpq.Limit(2).All(setContextOp(ctx, lpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lab_problem.Label}
	default:
		return nil, &NotSingularError{lab_problem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lpq *LabProblemQuery) OnlyX(ctx context.Context) *Lab_Problem {
	node, err := lpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Lab_Problem ID in the query.
// Returns a *NotSingularError when more than one Lab_Problem ID is found.
// Returns a *NotFoundError when no entities are found.
func (lpq *LabProblemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lpq.Limit(2).IDs(setContextOp(ctx, lpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lab_problem.Label}
	default:
		err = &NotSingularError{lab_problem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lpq *LabProblemQuery) OnlyIDX(ctx context.Context) int {
	id, err := lpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Lab_Problems.
func (lpq *LabProblemQuery) All(ctx context.Context) ([]*Lab_Problem, error) {
	ctx = setContextOp(ctx, lpq.ctx, "All")
	if err := lpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lab_Problem, *LabProblemQuery]()
	return withInterceptors[[]*Lab_Problem](ctx, lpq, qr, lpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lpq *LabProblemQuery) AllX(ctx context.Context) []*Lab_Problem {
	nodes, err := lpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Lab_Problem IDs.
func (lpq *LabProblemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lpq.ctx.Unique == nil && lpq.path != nil {
		lpq.Unique(true)
	}
	ctx = setContextOp(ctx, lpq.ctx, "IDs")
	if err = lpq.Select(lab_problem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lpq *LabProblemQuery) IDsX(ctx context.Context) []int {
	ids, err := lpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lpq *LabProblemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lpq.ctx, "Count")
	if err := lpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lpq, querierCount[*LabProblemQuery](), lpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lpq *LabProblemQuery) CountX(ctx context.Context) int {
	count, err := lpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lpq *LabProblemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lpq.ctx, "Exist")
	switch _, err := lpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lpq *LabProblemQuery) ExistX(ctx context.Context) bool {
	exist, err := lpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LabProblemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lpq *LabProblemQuery) Clone() *LabProblemQuery {
	if lpq == nil {
		return nil
	}
	return &LabProblemQuery{
		config:        lpq.config,
		ctx:           lpq.ctx.Clone(),
		order:         append([]lab_problem.OrderOption{}, lpq.order...),
		inters:        append([]Interceptor{}, lpq.inters...),
		predicates:    append([]predicate.Lab_Problem{}, lpq.predicates...),
		withLab:       lpq.withLab.Clone(),
		withTestcases: lpq.withTestcases.Clone(),
		// clone intermediate query.
		sql:  lpq.sql.Clone(),
		path: lpq.path,
	}
}

// WithLab tells the query-builder to eager-load the nodes that are connected to
// the "lab" edge. The optional arguments are used to configure the query builder of the edge.
func (lpq *LabProblemQuery) WithLab(opts ...func(*LabQuery)) *LabProblemQuery {
	query := (&LabClient{config: lpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lpq.withLab = query
	return lpq
}

// WithTestcases tells the query-builder to eager-load the nodes that are connected to
// the "testcases" edge. The optional arguments are used to configure the query builder of the edge.
func (lpq *LabProblemQuery) WithTestcases(opts ...func(*TestcaseQuery)) *LabProblemQuery {
	query := (&TestcaseClient{config: lpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lpq.withTestcases = query
	return lpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LabID int `json:"lab_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LabProblem.Query().
//		GroupBy(lab_problem.FieldLabID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lpq *LabProblemQuery) GroupBy(field string, fields ...string) *LabProblemGroupBy {
	lpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LabProblemGroupBy{build: lpq}
	grbuild.flds = &lpq.ctx.Fields
	grbuild.label = lab_problem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LabID int `json:"lab_id,omitempty"`
//	}
//
//	client.LabProblem.Query().
//		Select(lab_problem.FieldLabID).
//		Scan(ctx, &v)
func (lpq *LabProblemQuery) Select(fields ...string) *LabProblemSelect {
	lpq.ctx.Fields = append(lpq.ctx.Fields, fields...)
	sbuild := &LabProblemSelect{LabProblemQuery: lpq}
	sbuild.label = lab_problem.Label
	sbuild.flds, sbuild.scan = &lpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LabProblemSelect configured with the given aggregations.
func (lpq *LabProblemQuery) Aggregate(fns ...AggregateFunc) *LabProblemSelect {
	return lpq.Select().Aggregate(fns...)
}

func (lpq *LabProblemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lpq); err != nil {
				return err
			}
		}
	}
	for _, f := range lpq.ctx.Fields {
		if !lab_problem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lpq.path != nil {
		prev, err := lpq.path(ctx)
		if err != nil {
			return err
		}
		lpq.sql = prev
	}
	return nil
}

func (lpq *LabProblemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lab_Problem, error) {
	var (
		nodes       = []*Lab_Problem{}
		_spec       = lpq.querySpec()
		loadedTypes = [2]bool{
			lpq.withLab != nil,
			lpq.withTestcases != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lab_Problem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lab_Problem{config: lpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lpq.withLab; query != nil {
		if err := lpq.loadLab(ctx, query, nodes, nil,
			func(n *Lab_Problem, e *Lab) { n.Edges.Lab = e }); err != nil {
			return nil, err
		}
	}
	if query := lpq.withTestcases; query != nil {
		if err := lpq.loadTestcases(ctx, query, nodes,
			func(n *Lab_Problem) { n.Edges.Testcases = []*Testcase{} },
			func(n *Lab_Problem, e *Testcase) { n.Edges.Testcases = append(n.Edges.Testcases, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lpq *LabProblemQuery) loadLab(ctx context.Context, query *LabQuery, nodes []*Lab_Problem, init func(*Lab_Problem), assign func(*Lab_Problem, *Lab)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Lab_Problem)
	for i := range nodes {
		fk := nodes[i].LabID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(lab.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lab_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (lpq *LabProblemQuery) loadTestcases(ctx context.Context, query *TestcaseQuery, nodes []*Lab_Problem, init func(*Lab_Problem), assign func(*Lab_Problem, *Testcase)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Lab_Problem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(testcase.FieldLabProblemID)
	}
	query.Where(predicate.Testcase(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lab_problem.TestcasesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LabProblemID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "lab_problem_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lpq *LabProblemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lpq.querySpec()
	_spec.Node.Columns = lpq.ctx.Fields
	if len(lpq.ctx.Fields) > 0 {
		_spec.Unique = lpq.ctx.Unique != nil && *lpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lpq.driver, _spec)
}

func (lpq *LabProblemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lab_problem.Table, lab_problem.Columns, sqlgraph.NewFieldSpec(lab_problem.FieldID, field.TypeInt))
	_spec.From = lpq.sql
	if unique := lpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lpq.path != nil {
		_spec.Unique = true
	}
	if fields := lpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lab_problem.FieldID)
		for i := range fields {
			if fields[i] != lab_problem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if lpq.withLab != nil {
			_spec.Node.AddColumnOnce(lab_problem.FieldLabID)
		}
	}
	if ps := lpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lpq *LabProblemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lpq.driver.Dialect())
	t1 := builder.Table(lab_problem.Table)
	columns := lpq.ctx.Fields
	if len(columns) == 0 {
		columns = lab_problem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lpq.sql != nil {
		selector = lpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lpq.ctx.Unique != nil && *lpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lpq.predicates {
		p(selector)
	}
	for _, p := range lpq.order {
		p(selector)
	}
	if offset := lpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LabProblemGroupBy is the group-by builder for Lab_Problem entities.
type LabProblemGroupBy struct {
	selector
	build *LabProblemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lpgb *LabProblemGroupBy) Aggregate(fns ...AggregateFunc) *LabProblemGroupBy {
	lpgb.fns = append(lpgb.fns, fns...)
	return lpgb
}

// Scan applies the selector query and scans the result into the given value.
func (lpgb *LabProblemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lpgb.build.ctx, "GroupBy")
	if err := lpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LabProblemQuery, *LabProblemGroupBy](ctx, lpgb.build, lpgb, lpgb.build.inters, v)
}

func (lpgb *LabProblemGroupBy) sqlScan(ctx context.Context, root *LabProblemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lpgb.fns))
	for _, fn := range lpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lpgb.flds)+len(lpgb.fns))
		for _, f := range *lpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LabProblemSelect is the builder for selecting fields of LabProblem entities.
type LabProblemSelect struct {
	*LabProblemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lps *LabProblemSelect) Aggregate(fns ...AggregateFunc) *LabProblemSelect {
	lps.fns = append(lps.fns, fns...)
	return lps
}

// Scan applies the selector query and scans the result into the given value.
func (lps *LabProblemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lps.ctx, "Select")
	if err := lps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LabProblemQuery, *LabProblemSelect](ctx, lps.LabProblemQuery, lps, lps.inters, v)
}

func (lps *LabProblemSelect) sqlScan(ctx context.Context, root *LabProblemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lps.fns))
	for _, fn := range lps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
