// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plms-backend/ent/class_lab_status"
	"plms-backend/ent/course"
	"plms-backend/ent/lab"
	"plms-backend/ent/lab_problem"
	"plms-backend/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LabQuery is the builder for querying Lab entities.
type LabQuery struct {
	config
	ctx             *QueryContext
	order           []lab.OrderOption
	inters          []Interceptor
	predicates      []predicate.Lab
	withCourse      *CourseQuery
	withLabProblems *LabProblemQuery
	withLabStatuses *ClassLabStatusQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LabQuery builder.
func (lq *LabQuery) Where(ps ...predicate.Lab) *LabQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit the number of records to be returned by this query.
func (lq *LabQuery) Limit(limit int) *LabQuery {
	lq.ctx.Limit = &limit
	return lq
}

// Offset to start from.
func (lq *LabQuery) Offset(offset int) *LabQuery {
	lq.ctx.Offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LabQuery) Unique(unique bool) *LabQuery {
	lq.ctx.Unique = &unique
	return lq
}

// Order specifies how the records should be ordered.
func (lq *LabQuery) Order(o ...lab.OrderOption) *LabQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QueryCourse chains the current query on the "course" edge.
func (lq *LabQuery) QueryCourse() *CourseQuery {
	query := (&CourseClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lab.Table, lab.FieldID, selector),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, lab.CourseTable, lab.CourseColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLabProblems chains the current query on the "lab_problems" edge.
func (lq *LabQuery) QueryLabProblems() *LabProblemQuery {
	query := (&LabProblemClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lab.Table, lab.FieldID, selector),
			sqlgraph.To(lab_problem.Table, lab_problem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lab.LabProblemsTable, lab.LabProblemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLabStatuses chains the current query on the "lab_statuses" edge.
func (lq *LabQuery) QueryLabStatuses() *ClassLabStatusQuery {
	query := (&ClassLabStatusClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lab.Table, lab.FieldID, selector),
			sqlgraph.To(class_lab_status.Table, class_lab_status.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lab.LabStatusesTable, lab.LabStatusesColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lab entity from the query.
// Returns a *NotFoundError when no Lab was found.
func (lq *LabQuery) First(ctx context.Context) (*Lab, error) {
	nodes, err := lq.Limit(1).All(setContextOp(ctx, lq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lab.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LabQuery) FirstX(ctx context.Context) *Lab {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Lab ID from the query.
// Returns a *NotFoundError when no Lab ID was found.
func (lq *LabQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lq.Limit(1).IDs(setContextOp(ctx, lq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lab.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lq *LabQuery) FirstIDX(ctx context.Context) int {
	id, err := lq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lab entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lab entity is found.
// Returns a *NotFoundError when no Lab entities are found.
func (lq *LabQuery) Only(ctx context.Context) (*Lab, error) {
	nodes, err := lq.Limit(2).All(setContextOp(ctx, lq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lab.Label}
	default:
		return nil, &NotSingularError{lab.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LabQuery) OnlyX(ctx context.Context) *Lab {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Lab ID in the query.
// Returns a *NotSingularError when more than one Lab ID is found.
// Returns a *NotFoundError when no entities are found.
func (lq *LabQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lq.Limit(2).IDs(setContextOp(ctx, lq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lab.Label}
	default:
		err = &NotSingularError{lab.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lq *LabQuery) OnlyIDX(ctx context.Context) int {
	id, err := lq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Labs.
func (lq *LabQuery) All(ctx context.Context) ([]*Lab, error) {
	ctx = setContextOp(ctx, lq.ctx, "All")
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lab, *LabQuery]()
	return withInterceptors[[]*Lab](ctx, lq, qr, lq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lq *LabQuery) AllX(ctx context.Context) []*Lab {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Lab IDs.
func (lq *LabQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lq.ctx.Unique == nil && lq.path != nil {
		lq.Unique(true)
	}
	ctx = setContextOp(ctx, lq.ctx, "IDs")
	if err = lq.Select(lab.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lq *LabQuery) IDsX(ctx context.Context) []int {
	ids, err := lq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lq *LabQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lq.ctx, "Count")
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lq, querierCount[*LabQuery](), lq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LabQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LabQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lq.ctx, "Exist")
	switch _, err := lq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LabQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LabQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LabQuery) Clone() *LabQuery {
	if lq == nil {
		return nil
	}
	return &LabQuery{
		config:          lq.config,
		ctx:             lq.ctx.Clone(),
		order:           append([]lab.OrderOption{}, lq.order...),
		inters:          append([]Interceptor{}, lq.inters...),
		predicates:      append([]predicate.Lab{}, lq.predicates...),
		withCourse:      lq.withCourse.Clone(),
		withLabProblems: lq.withLabProblems.Clone(),
		withLabStatuses: lq.withLabStatuses.Clone(),
		// clone intermediate query.
		sql:  lq.sql.Clone(),
		path: lq.path,
	}
}

// WithCourse tells the query-builder to eager-load the nodes that are connected to
// the "course" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LabQuery) WithCourse(opts ...func(*CourseQuery)) *LabQuery {
	query := (&CourseClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withCourse = query
	return lq
}

// WithLabProblems tells the query-builder to eager-load the nodes that are connected to
// the "lab_problems" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LabQuery) WithLabProblems(opts ...func(*LabProblemQuery)) *LabQuery {
	query := (&LabProblemClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withLabProblems = query
	return lq
}

// WithLabStatuses tells the query-builder to eager-load the nodes that are connected to
// the "lab_statuses" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LabQuery) WithLabStatuses(opts ...func(*ClassLabStatusQuery)) *LabQuery {
	query := (&ClassLabStatusClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withLabStatuses = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CourseID int `json:"course_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lab.Query().
//		GroupBy(lab.FieldCourseID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lq *LabQuery) GroupBy(field string, fields ...string) *LabGroupBy {
	lq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LabGroupBy{build: lq}
	grbuild.flds = &lq.ctx.Fields
	grbuild.label = lab.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CourseID int `json:"course_id,omitempty"`
//	}
//
//	client.Lab.Query().
//		Select(lab.FieldCourseID).
//		Scan(ctx, &v)
func (lq *LabQuery) Select(fields ...string) *LabSelect {
	lq.ctx.Fields = append(lq.ctx.Fields, fields...)
	sbuild := &LabSelect{LabQuery: lq}
	sbuild.label = lab.Label
	sbuild.flds, sbuild.scan = &lq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LabSelect configured with the given aggregations.
func (lq *LabQuery) Aggregate(fns ...AggregateFunc) *LabSelect {
	return lq.Select().Aggregate(fns...)
}

func (lq *LabQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lq); err != nil {
				return err
			}
		}
	}
	for _, f := range lq.ctx.Fields {
		if !lab.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LabQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lab, error) {
	var (
		nodes       = []*Lab{}
		_spec       = lq.querySpec()
		loadedTypes = [3]bool{
			lq.withCourse != nil,
			lq.withLabProblems != nil,
			lq.withLabStatuses != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lab).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lab{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withCourse; query != nil {
		if err := lq.loadCourse(ctx, query, nodes, nil,
			func(n *Lab, e *Course) { n.Edges.Course = e }); err != nil {
			return nil, err
		}
	}
	if query := lq.withLabProblems; query != nil {
		if err := lq.loadLabProblems(ctx, query, nodes,
			func(n *Lab) { n.Edges.LabProblems = []*Lab_Problem{} },
			func(n *Lab, e *Lab_Problem) { n.Edges.LabProblems = append(n.Edges.LabProblems, e) }); err != nil {
			return nil, err
		}
	}
	if query := lq.withLabStatuses; query != nil {
		if err := lq.loadLabStatuses(ctx, query, nodes,
			func(n *Lab) { n.Edges.LabStatuses = []*Class_Lab_Status{} },
			func(n *Lab, e *Class_Lab_Status) { n.Edges.LabStatuses = append(n.Edges.LabStatuses, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LabQuery) loadCourse(ctx context.Context, query *CourseQuery, nodes []*Lab, init func(*Lab), assign func(*Lab, *Course)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Lab)
	for i := range nodes {
		fk := nodes[i].CourseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(course.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (lq *LabQuery) loadLabProblems(ctx context.Context, query *LabProblemQuery, nodes []*Lab, init func(*Lab), assign func(*Lab, *Lab_Problem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Lab)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(lab_problem.FieldLabID)
	}
	query.Where(predicate.Lab_Problem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lab.LabProblemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LabID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "lab_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (lq *LabQuery) loadLabStatuses(ctx context.Context, query *ClassLabStatusQuery, nodes []*Lab, init func(*Lab), assign func(*Lab, *Class_Lab_Status)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Lab)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(class_lab_status.FieldLabID)
	}
	query.Where(predicate.Class_Lab_Status(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lab.LabStatusesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LabID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "lab_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lq *LabQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Node.Columns = lq.ctx.Fields
	if len(lq.ctx.Fields) > 0 {
		_spec.Unique = lq.ctx.Unique != nil && *lq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LabQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lab.Table, lab.Columns, sqlgraph.NewFieldSpec(lab.FieldID, field.TypeInt))
	_spec.From = lq.sql
	if unique := lq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lq.path != nil {
		_spec.Unique = true
	}
	if fields := lq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lab.FieldID)
		for i := range fields {
			if fields[i] != lab.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if lq.withCourse != nil {
			_spec.Node.AddColumnOnce(lab.FieldCourseID)
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LabQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(lab.Table)
	columns := lq.ctx.Fields
	if len(columns) == 0 {
		columns = lab.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.ctx.Unique != nil && *lq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LabGroupBy is the group-by builder for Lab entities.
type LabGroupBy struct {
	selector
	build *LabQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LabGroupBy) Aggregate(fns ...AggregateFunc) *LabGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the selector query and scans the result into the given value.
func (lgb *LabGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lgb.build.ctx, "GroupBy")
	if err := lgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LabQuery, *LabGroupBy](ctx, lgb.build, lgb, lgb.build.inters, v)
}

func (lgb *LabGroupBy) sqlScan(ctx context.Context, root *LabQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lgb.flds)+len(lgb.fns))
		for _, f := range *lgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LabSelect is the builder for selecting fields of Lab entities.
type LabSelect struct {
	*LabQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ls *LabSelect) Aggregate(fns ...AggregateFunc) *LabSelect {
	ls.fns = append(ls.fns, fns...)
	return ls
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LabSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ls.ctx, "Select")
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LabQuery, *LabSelect](ctx, ls.LabQuery, ls, ls.inters, v)
}

func (ls *LabSelect) sqlScan(ctx context.Context, root *LabQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ls.fns))
	for _, fn := range ls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
