// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plms-backend/ent/predicate"
	"plms-backend/ent/testcase_submission"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestcaseSubmissionDelete is the builder for deleting a Testcase_Submission entity.
type TestcaseSubmissionDelete struct {
	config
	hooks    []Hook
	mutation *TestcaseSubmissionMutation
}

// Where appends a list predicates to the TestcaseSubmissionDelete builder.
func (tsd *TestcaseSubmissionDelete) Where(ps ...predicate.Testcase_Submission) *TestcaseSubmissionDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TestcaseSubmissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TestcaseSubmissionDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TestcaseSubmissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(testcase_submission.Table, sqlgraph.NewFieldSpec(testcase_submission.FieldID, field.TypeInt))
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TestcaseSubmissionDeleteOne is the builder for deleting a single Testcase_Submission entity.
type TestcaseSubmissionDeleteOne struct {
	tsd *TestcaseSubmissionDelete
}

// Where appends a list predicates to the TestcaseSubmissionDelete builder.
func (tsdo *TestcaseSubmissionDeleteOne) Where(ps ...predicate.Testcase_Submission) *TestcaseSubmissionDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TestcaseSubmissionDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{testcase_submission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TestcaseSubmissionDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
