// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plms-backend/ent/predicate"
	"plms-backend/ent/topic"
	"plms-backend/ent/topic_file_mats"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TopicFileMatsQuery is the builder for querying Topic_File_Mats entities.
type TopicFileMatsQuery struct {
	config
	ctx        *QueryContext
	order      []topic_file_mats.OrderOption
	inters     []Interceptor
	predicates []predicate.Topic_File_Mats
	withTopic  *TopicQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TopicFileMatsQuery builder.
func (tfmq *TopicFileMatsQuery) Where(ps ...predicate.Topic_File_Mats) *TopicFileMatsQuery {
	tfmq.predicates = append(tfmq.predicates, ps...)
	return tfmq
}

// Limit the number of records to be returned by this query.
func (tfmq *TopicFileMatsQuery) Limit(limit int) *TopicFileMatsQuery {
	tfmq.ctx.Limit = &limit
	return tfmq
}

// Offset to start from.
func (tfmq *TopicFileMatsQuery) Offset(offset int) *TopicFileMatsQuery {
	tfmq.ctx.Offset = &offset
	return tfmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tfmq *TopicFileMatsQuery) Unique(unique bool) *TopicFileMatsQuery {
	tfmq.ctx.Unique = &unique
	return tfmq
}

// Order specifies how the records should be ordered.
func (tfmq *TopicFileMatsQuery) Order(o ...topic_file_mats.OrderOption) *TopicFileMatsQuery {
	tfmq.order = append(tfmq.order, o...)
	return tfmq
}

// QueryTopic chains the current query on the "topic" edge.
func (tfmq *TopicFileMatsQuery) QueryTopic() *TopicQuery {
	query := (&TopicClient{config: tfmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tfmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tfmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(topic_file_mats.Table, topic_file_mats.FieldID, selector),
			sqlgraph.To(topic.Table, topic.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, topic_file_mats.TopicTable, topic_file_mats.TopicColumn),
		)
		fromU = sqlgraph.SetNeighbors(tfmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Topic_File_Mats entity from the query.
// Returns a *NotFoundError when no Topic_File_Mats was found.
func (tfmq *TopicFileMatsQuery) First(ctx context.Context) (*Topic_File_Mats, error) {
	nodes, err := tfmq.Limit(1).All(setContextOp(ctx, tfmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{topic_file_mats.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) FirstX(ctx context.Context) *Topic_File_Mats {
	node, err := tfmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Topic_File_Mats ID from the query.
// Returns a *NotFoundError when no Topic_File_Mats ID was found.
func (tfmq *TopicFileMatsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tfmq.Limit(1).IDs(setContextOp(ctx, tfmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{topic_file_mats.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) FirstIDX(ctx context.Context) int {
	id, err := tfmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Topic_File_Mats entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Topic_File_Mats entity is found.
// Returns a *NotFoundError when no Topic_File_Mats entities are found.
func (tfmq *TopicFileMatsQuery) Only(ctx context.Context) (*Topic_File_Mats, error) {
	nodes, err := tfmq.Limit(2).All(setContextOp(ctx, tfmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{topic_file_mats.Label}
	default:
		return nil, &NotSingularError{topic_file_mats.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) OnlyX(ctx context.Context) *Topic_File_Mats {
	node, err := tfmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Topic_File_Mats ID in the query.
// Returns a *NotSingularError when more than one Topic_File_Mats ID is found.
// Returns a *NotFoundError when no entities are found.
func (tfmq *TopicFileMatsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tfmq.Limit(2).IDs(setContextOp(ctx, tfmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{topic_file_mats.Label}
	default:
		err = &NotSingularError{topic_file_mats.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) OnlyIDX(ctx context.Context) int {
	id, err := tfmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Topic_File_MatsSlice.
func (tfmq *TopicFileMatsQuery) All(ctx context.Context) ([]*Topic_File_Mats, error) {
	ctx = setContextOp(ctx, tfmq.ctx, "All")
	if err := tfmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Topic_File_Mats, *TopicFileMatsQuery]()
	return withInterceptors[[]*Topic_File_Mats](ctx, tfmq, qr, tfmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) AllX(ctx context.Context) []*Topic_File_Mats {
	nodes, err := tfmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Topic_File_Mats IDs.
func (tfmq *TopicFileMatsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tfmq.ctx.Unique == nil && tfmq.path != nil {
		tfmq.Unique(true)
	}
	ctx = setContextOp(ctx, tfmq.ctx, "IDs")
	if err = tfmq.Select(topic_file_mats.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) IDsX(ctx context.Context) []int {
	ids, err := tfmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tfmq *TopicFileMatsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tfmq.ctx, "Count")
	if err := tfmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tfmq, querierCount[*TopicFileMatsQuery](), tfmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) CountX(ctx context.Context) int {
	count, err := tfmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tfmq *TopicFileMatsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tfmq.ctx, "Exist")
	switch _, err := tfmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tfmq *TopicFileMatsQuery) ExistX(ctx context.Context) bool {
	exist, err := tfmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TopicFileMatsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tfmq *TopicFileMatsQuery) Clone() *TopicFileMatsQuery {
	if tfmq == nil {
		return nil
	}
	return &TopicFileMatsQuery{
		config:     tfmq.config,
		ctx:        tfmq.ctx.Clone(),
		order:      append([]topic_file_mats.OrderOption{}, tfmq.order...),
		inters:     append([]Interceptor{}, tfmq.inters...),
		predicates: append([]predicate.Topic_File_Mats{}, tfmq.predicates...),
		withTopic:  tfmq.withTopic.Clone(),
		// clone intermediate query.
		sql:  tfmq.sql.Clone(),
		path: tfmq.path,
	}
}

// WithTopic tells the query-builder to eager-load the nodes that are connected to
// the "topic" edge. The optional arguments are used to configure the query builder of the edge.
func (tfmq *TopicFileMatsQuery) WithTopic(opts ...func(*TopicQuery)) *TopicFileMatsQuery {
	query := (&TopicClient{config: tfmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tfmq.withTopic = query
	return tfmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TopicID int `json:"topic_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TopicFileMats.Query().
//		GroupBy(topic_file_mats.FieldTopicID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tfmq *TopicFileMatsQuery) GroupBy(field string, fields ...string) *TopicFileMatsGroupBy {
	tfmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TopicFileMatsGroupBy{build: tfmq}
	grbuild.flds = &tfmq.ctx.Fields
	grbuild.label = topic_file_mats.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TopicID int `json:"topic_id,omitempty"`
//	}
//
//	client.TopicFileMats.Query().
//		Select(topic_file_mats.FieldTopicID).
//		Scan(ctx, &v)
func (tfmq *TopicFileMatsQuery) Select(fields ...string) *TopicFileMatsSelect {
	tfmq.ctx.Fields = append(tfmq.ctx.Fields, fields...)
	sbuild := &TopicFileMatsSelect{TopicFileMatsQuery: tfmq}
	sbuild.label = topic_file_mats.Label
	sbuild.flds, sbuild.scan = &tfmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TopicFileMatsSelect configured with the given aggregations.
func (tfmq *TopicFileMatsQuery) Aggregate(fns ...AggregateFunc) *TopicFileMatsSelect {
	return tfmq.Select().Aggregate(fns...)
}

func (tfmq *TopicFileMatsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tfmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tfmq); err != nil {
				return err
			}
		}
	}
	for _, f := range tfmq.ctx.Fields {
		if !topic_file_mats.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tfmq.path != nil {
		prev, err := tfmq.path(ctx)
		if err != nil {
			return err
		}
		tfmq.sql = prev
	}
	return nil
}

func (tfmq *TopicFileMatsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Topic_File_Mats, error) {
	var (
		nodes       = []*Topic_File_Mats{}
		_spec       = tfmq.querySpec()
		loadedTypes = [1]bool{
			tfmq.withTopic != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Topic_File_Mats).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Topic_File_Mats{config: tfmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tfmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tfmq.withTopic; query != nil {
		if err := tfmq.loadTopic(ctx, query, nodes, nil,
			func(n *Topic_File_Mats, e *Topic) { n.Edges.Topic = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tfmq *TopicFileMatsQuery) loadTopic(ctx context.Context, query *TopicQuery, nodes []*Topic_File_Mats, init func(*Topic_File_Mats), assign func(*Topic_File_Mats, *Topic)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Topic_File_Mats)
	for i := range nodes {
		fk := nodes[i].TopicID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(topic.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "topic_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tfmq *TopicFileMatsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tfmq.querySpec()
	_spec.Node.Columns = tfmq.ctx.Fields
	if len(tfmq.ctx.Fields) > 0 {
		_spec.Unique = tfmq.ctx.Unique != nil && *tfmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tfmq.driver, _spec)
}

func (tfmq *TopicFileMatsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(topic_file_mats.Table, topic_file_mats.Columns, sqlgraph.NewFieldSpec(topic_file_mats.FieldID, field.TypeInt))
	_spec.From = tfmq.sql
	if unique := tfmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tfmq.path != nil {
		_spec.Unique = true
	}
	if fields := tfmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, topic_file_mats.FieldID)
		for i := range fields {
			if fields[i] != topic_file_mats.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tfmq.withTopic != nil {
			_spec.Node.AddColumnOnce(topic_file_mats.FieldTopicID)
		}
	}
	if ps := tfmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tfmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tfmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tfmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tfmq *TopicFileMatsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tfmq.driver.Dialect())
	t1 := builder.Table(topic_file_mats.Table)
	columns := tfmq.ctx.Fields
	if len(columns) == 0 {
		columns = topic_file_mats.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tfmq.sql != nil {
		selector = tfmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tfmq.ctx.Unique != nil && *tfmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tfmq.predicates {
		p(selector)
	}
	for _, p := range tfmq.order {
		p(selector)
	}
	if offset := tfmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tfmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TopicFileMatsGroupBy is the group-by builder for Topic_File_Mats entities.
type TopicFileMatsGroupBy struct {
	selector
	build *TopicFileMatsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tfmgb *TopicFileMatsGroupBy) Aggregate(fns ...AggregateFunc) *TopicFileMatsGroupBy {
	tfmgb.fns = append(tfmgb.fns, fns...)
	return tfmgb
}

// Scan applies the selector query and scans the result into the given value.
func (tfmgb *TopicFileMatsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tfmgb.build.ctx, "GroupBy")
	if err := tfmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TopicFileMatsQuery, *TopicFileMatsGroupBy](ctx, tfmgb.build, tfmgb, tfmgb.build.inters, v)
}

func (tfmgb *TopicFileMatsGroupBy) sqlScan(ctx context.Context, root *TopicFileMatsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tfmgb.fns))
	for _, fn := range tfmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tfmgb.flds)+len(tfmgb.fns))
		for _, f := range *tfmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tfmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tfmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TopicFileMatsSelect is the builder for selecting fields of TopicFileMats entities.
type TopicFileMatsSelect struct {
	*TopicFileMatsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tfms *TopicFileMatsSelect) Aggregate(fns ...AggregateFunc) *TopicFileMatsSelect {
	tfms.fns = append(tfms.fns, fns...)
	return tfms
}

// Scan applies the selector query and scans the result into the given value.
func (tfms *TopicFileMatsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tfms.ctx, "Select")
	if err := tfms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TopicFileMatsQuery, *TopicFileMatsSelect](ctx, tfms.TopicFileMatsQuery, tfms, tfms.inters, v)
}

func (tfms *TopicFileMatsSelect) sqlScan(ctx context.Context, root *TopicFileMatsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tfms.fns))
	for _, fn := range tfms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tfms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tfms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
