// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Class is the predicate function for class builders.
type Class func(*sql.Selector)

// Class_Lab_Status is the predicate function for class_lab_status builders.
type Class_Lab_Status func(*sql.Selector)

// Class_User_Role is the predicate function for class_user_role builders.
type Class_User_Role func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Lab is the predicate function for lab builders.
type Lab func(*sql.Selector)

// Lab_Problem is the predicate function for lab_problem builders.
type Lab_Problem func(*sql.Selector)

// Lab_Problem_Submission is the predicate function for lab_problem_submission builders.
type Lab_Problem_Submission func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Testcase is the predicate function for testcase builders.
type Testcase func(*sql.Selector)

// Testcase_Submission is the predicate function for testcase_submission builders.
type Testcase_Submission func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)

// Topic_File_Mats is the predicate function for topic_file_mats builders.
type Topic_File_Mats func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
